package com.example.dylan.module.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.dylan.module.entity.Pictures;
import com.example.dylan.module.entity.User;
import com.example.dylan.module.greendao.InitDaoMaster;

import com.example.dylan.module.dao.PicturesDao;
import com.example.dylan.module.dao.UserDao;
import com.example.dylan.module.dao.InitDaoMasterDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig picturesDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig initDaoMasterDaoConfig;

    private final PicturesDao picturesDao;
    private final UserDao userDao;
    private final InitDaoMasterDao initDaoMasterDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        picturesDaoConfig = daoConfigMap.get(PicturesDao.class).clone();
        picturesDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        initDaoMasterDaoConfig = daoConfigMap.get(InitDaoMasterDao.class).clone();
        initDaoMasterDaoConfig.initIdentityScope(type);

        picturesDao = new PicturesDao(picturesDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        initDaoMasterDao = new InitDaoMasterDao(initDaoMasterDaoConfig, this);

        registerDao(Pictures.class, picturesDao);
        registerDao(User.class, userDao);
        registerDao(InitDaoMaster.class, initDaoMasterDao);
    }
    
    public void clear() {
        picturesDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        initDaoMasterDaoConfig.clearIdentityScope();
    }

    public PicturesDao getPicturesDao() {
        return picturesDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public InitDaoMasterDao getInitDaoMasterDao() {
        return initDaoMasterDao;
    }

}
